spring:
  application:
    name: devup
  profiles:
    active: dev

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:devup;MODE=MySQL;
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  sql:
    init:
      mode: always
  thymeleaf:
  thymeleaf3:
    decoupled-logic: true

server:
  port: 8080

jwt:
  secret_key: ${JWT_SECRET_KEY}
  issuer: ${JWT_ISSUER}
  expiration: ${JWT_EXPIRATION}

security:
  csrf-enabled: false


---

spring:
  config:
    activate:
      on-profile: prod

security:
  csrf-enabled: true