spring:
  application:
    name: devup
  profiles:
    active: dev
    group:
      dev:
        - common
      prod:
        - common
---

spring:
  config:
    activate:
      on-profile: common
  thymeleaf3:
    decoupled-logic: true

jwt:
  secret_key: ${JWT_SECRET_KEY}
  issuer: ${JWT_ISSUER}
  expiration: ${JWT_EXPIRATION}

cookie:
  secure: false
  access-token-max-age: 3600

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:devup;MODE=MySQL;
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  sql:
    init:
      mode: always


server:
  port: 8080

security:
  csrf-enabled: false

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DB_URL}
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 101
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

server:
  tomcat:
    threads:
      max: 100
  port: 8080

security:
  csrf-enabled: false