name: CI/CD

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      DB_URL: ${ { secrets.DB_URL } }
      DB_USERNAME: ${ { secrets.DB_USERNAME } }
      DB_PASSWORD: ${ { secrets.DB_PASSWORD } }

    steps:
      # CI
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        uses: ./gradlew clean build

      # CD
      - name: Copy JAR to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${ { secrets.EC2_HOST } }
          username: ${ { secrets.EC2_USER } }
          key: ${ { secrets.EC2_KEY } }
          source: build/libs/devup.jar
          target: /home/ec2-user/app/

      - name: Restart service
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${ { secrets.EC2_HOST } }
          username: ${ { secrets.EC2_USER } }
          key: ${ { secrets.EC2_KEY } }
          script: |
            sudo systemctl daemon-reload
            sudo systemctl restart devup